### ISSUE TITLE
Inconsistent definition of slice and fiber

### ISSUE THREAD

**Issue by JiyuFang-git** [IlyaKisil/dpm-coursework#1]
Hi!

For the following definition of fiber and slice, the code example seems to be inconsistent with the description above.

![image](https://user-images.githubusercontent.com/24462863/55355928-7b908180-54c1-11e9-8013-5cd9685a9488.png)

For example, for mode-2 fiber, shouldn't the correct indexing be [0,:,1]?

**Comment by IlyaKisil** [comment]
Hi @IceyFong, thanks for pointing this out. Inconsistency between image and code snippets comes from the fact that indexing in python starts from 0 whereas on image count starts from 1. 

Let's adopt notation and definition as shown on image, since in other parts of this assignment use terms horizontal/frontal slices.

**Comment by JiyuFang-git** [comment]
So you mean that for frontal slice it should be tensor.data[:,:,k]? 

However the code snippet shown seems using the definition of mode-[1,2] slice.

**Comment by IlyaKisil** [comment]
Yes, use `tensor.data[:,:,k]` and disregard code snippet
